# Generated by Django 5.2 on 2025-04-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('cost', models.FloatField(default=0.0)),
                ('interests', models.JSONField()),
                ('season', models.CharField(default='Year-round', max_length=50)),
                ('location', models.CharField(default='Ethiopia', max_length=100)),
            ],
        ),
    ]
